bremersee:
  ldaptive:
    ldap-url: ${LDAP_URL:ldaps://example.org:636}
    use-ssl: ${LDAP_SSL:true}
    use-start-tls: ${LDAP_START_TLS:false}
    bind-dn: ${LDAP_BIND_DN:areader@example.org}
    bind-credential: ${LDAP_BIND_PASSWORD:changeit}
    pooled: true
    min-pool-size: 3
    max-pool-size: 10
    validate-on-check-in: false
    validate-on-check-out: false
    validate-periodically: true
    validate-period: 300
    idle-time: 600
    block-wait-time: 10000
    search-validator:
      search-request:
        base-dn: ${LDAP_BASE_DN:dc=example,dc=org}
        search-filter:
          filter: ${LDAP_VALIDATION_FILTER:(cn=Administrator)}
        size-limit: 1
        search-scope: ONELEVEL
        return-attributes:
          - cn
  samba-domain:
    group-base-dn: ${LDAP_GROUP_DN:cn=Groups,dc=example,dc=org}
    user-base-dn: ${LDAP_USER_DN:cn=Users,dc=example,dc=org}

logging:
  level:
    ROOT: info
    org.bremersee: debug
    org.springframework: info
#    org.springframework.security.oauth2: debug

server:
  port: ${SERVER_PORT:8090}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Europe/Berlin

---

spring:
  profiles: debian9

logging:
  path: /var/log/smb-con
  file:
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/smb-con

