#!/usr/bin/env bash

/usr/bin/getent passwd smb-con
if [ ! $? -eq 0 ]; then
  /usr/sbin/adduser --system --home /var/lib/smb-con --shell /bin/false --no-create-home --group --disabled-login smb-con
fi

/bin/mkdir -p /var/lib/smb-con
/bin/chown -R smb-con:smb-con /var/lib/smb-con
/bin/chmod -R u+rwx /var/lib/smb-con

/bin/mkdir -p /var/log/smb-con
/bin/chown -R smb-con:smb-con /var/log/smb-con
/bin/chmod u+rwx /var/log/smb-con

if [ ! -e /etc/systemd/system/smb-con.service ]; then
  ln -s /lib/systemd/system/smb-con.service /etc/systemd/system/smb-con.service
fi
/bin/systemctl enable smb-con.service
/bin/systemctl start smb-con.service

exit 0