bremersee:
  authorization-server:
    allow-form-authentication-for-clients: false
    check-token-access: isAuthenticated()
    handle-approval-revocations-as-expiry: false
    jwt-key-pair-alias: ${JWT_KEY_PAIR_ALIAS:jwt}
    jwt-key-pair-password: ${JWT_KEY_PAIR_PASSWORD:changeit}
    jwt-key-store-location: ${JWT_KEY_STORE_LOCATION:classpath:jwt.jks}
    jwt-key-store-password: ${JWT_KEY_STORE_PASSWORD:changeit}
    no-scope-description-available: Sorry, there's no description of this scope.
    realm: ${REALM:oauth2/client}
    ssl-only: false
    token-key-access: permitAll()
  oauth2:
    facebook:
      provider: facebook
      login-url-template: "\
        https://www.facebook.com/v2.8/dialog/oauth\
        ?client_id={clientId}\
        &redirect_uri={redirectUri}\
        &response_type={responseType}\
        &scope={scope}\
        &state={state}"
      client-id: ${FACEBOOK_CLIENT_ID:changeit}
      client-secret: ${FACEBOOK_CLIENT_SECRET:changeit}
      redirect-uri: http://localhost:${server.port}${server.servlet.context-path}/facebook/callback
      response-type: code
      scope: public_profile,email
      token-url-template: "\
        https://graph.facebook.com/v2.8/oauth/access_token\
        ?client_id={clientId}\
        &redirect_uri={redirectUri}\
        &client_secret={clientSecret}\
        &code={code}"
      api-base-url: https://graph.facebook.com/v2.8
      profile-path-template: "/me?access_token={accessToken}\
        &fields=id,name,gender,first_name,middle_name,last_name,name_format,email,locale,timezone,verified,website"
    github:
      provider: github
      login-url-template: "\
        https://github.com/login/oauth/authorize\
        ?client_id={clientId}\
        &redirect_uri={redirectUri}\
        &scope={scope}\
        &state={state}"
      client-id: ${GITHUB_CLIENT_ID:changeit}
      client-secret: ${GITHUB_CLIENT_SECRET:changeit}
      redirect-uri: http://localhost:${server.port}${server.servlet.context-path}/github/callback
      response-type: code
      scope: user
      token-url-template: "\
        https://github.com/login/oauth/access_token\
        ?client_id={clientId}\
        &client_secret={clientSecret}\
        &redirect_uri={redirectUri}\
        &code={code}"
      token-method: POST
      api-base-url: https://api.github.com
      profile-path-template: /user?access_token={accessToken}
    google:
      provider: google
      login-url-template: "\
        https://accounts.google.com/o/oauth2/v2/auth\
        ?client_id={clientId}\
        &redirect_uri={redirectUri}\
        &response_type={responseType}\
        &scope={scope}\
        &state={state}\
        &access_type={accessType}\
        &include_granted_scopes={includeGrantedScopes}"
      client-id: ${GOOGLE_CLIENT_ID:changeit}
      client-secret: ${GOOGLE_CLIENT_SECRET:changeit}
      redirect-uri: http://localhost:${server.port}${server.servlet.context-path}/google/callback
      response-type: code
      scope: profile email
      additional-login-parameters:
        includeGrantedScopes: false
        accessType: online
#        accessType: offline
      token-url-template: "\
        https://www.googleapis.com/oauth2/v4/token\
        ?client_id={clientId}\
        &client_secret={clientSecret}\
        &redirect_uri={redirectUri}\
        &code={code}\
        &grant_type=authorization_code"
      token-method: POST
      api-base-url: https://www.googleapis.com
      profile-path-template: /plus/v1/people/me?access_token={accessToken}
  registration:
    life-time: 30
    life-time-unit: days
    link: http://localhost:${server.port}${server.servlet.context-path}/register?hash={registrationHash}
    sender: no-reply@bremersee.org
    subject-code: userRegistrationService.sendValidationEmail.subject
  samba-connector:
    name: smb-con
#    name: false
    url: http://localhost:8090
    token-endpoint: http://localhost:${server.port}${server.servlet.context-path}/oauth/token
  security:
    crypto:
      password-encoder:
        algorithm: SSHA256
        random-salt-length: 4
        store-no-encryption-flag: false
  sms:
    enabled: false
    url: https://gate1.goyyamobile.com/sms/sendsms.asp
    username: ${SMS_USERNAME:changeit}
    password: ${SMS_PASSWORD:changeit}
    sender: ${SMS_SENDER:bremersee}
  startup:
    admin:
      user-name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:secret4ADMIN}
      display-name: ${ADMIN_DISPLAY_NAME:Adam Admin}
      email: ${ADMIN_EMAIL:admin@bremersee.org}
      preferred-locale: ${ADMIN_LOCALE:de_DE}
      preferred-time-zone-id: ${ADMIN_TIME_ZONE:Europe/Berlin}
  user-service:
    min-search-length: ${USER_MIN_SEARCH_LENGTH:3}

feign:
  client:
    config:
      default:
        logger-level: FULL
        connect-timeout: 5000
        read-timeout: 5000
      smb-con:
        logger-level: FULL
        connect-timeout: 5000
        read-timeout: 5000

logging:
  level:
    ROOT: info
    org.bremersee: debug
    org.springframework: info

management:
  server:
    servlet:
      context-path: /management

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/authman}

spring:
  data:
    mongodb:
      database: auth
      host: localhost
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Europe/Berlin
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:no-reply@bremersee.org}
    password: ${MAIL_PASSWORD:changeit}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH:false}
      mail.smtp.ssl.enable: ${MAIL_SMTP_SSL_ENABLE:false}
  messages:
    basename: messages
  thymeleaf:
    cache: false
  zipkin:
    enabled: false
    base-url: http://zipkin:9411/

#  security:
#    oauth2:
#      client:
#        registration:
#          bremersee:
#            client-id: internal
#            client-secret: secret4INTERNAL
#            client-name: Client for user scope
#            provider: bremersee
#            scope:
#              - profile
#              - profile:write
#            redirect-uri-template: http://localhost:7080
#            client-authentication-method: basic
#            authorization-grant-type: authorization_code
#        provider:
#          bremersee:
#            authorization-uri: http://localhost:7080/oauth/authorize
#            token-uri: http://localhost:7080/oauth/token
#            user-info-uri: http://localhost:7080/api/me
#            jwk-set-uri: http://localhost:7080/token_keys
#            user-name-attribute: name

# curl -v --data "grant_type=refresh_token&client_id=THE_CLIENT_ID&refresh_token=THE_REFRESH_TOKEN" http://localhost:8080/oauth/token
